# Generated by Django 5.2.8 on 2025-11-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_unique_order_status_alter_order_id_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
